spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.113.172:3306/yzdx?useSSL=false
    username: root
    password: root
    tomcat.max-active: 100
    tomcat.max-idle: 100
    tomcat.initialSize: 20
  jpa:
    database: MYSQL
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true