spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.148.223.239:3306/yzdx?useSSL=false&serverTimezone=GMT
    username: yzdx
    password: yzdx
    tomcat.max-active: 100
    tomcat.max-idle: 100
    tomcat.initialSize: 20
  jpa:
    database: MYSQL
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true